version: '3.7'

services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3001:3000"
    volumes:
      - "./metabase-data:/metabase-data"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: pgdb
      MB_DB_FILE: /metabase-data/metabase.db
  db:
    image: postgres:14
    container_name: pgdb
    ports:
      - '5432:5432'
    env_file:
      - .env
  web:
    build:
      context: .
      args:
        flask_port: 5000
    container_name: web
    depends_on:
      - db
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: ["python", "app.py"]
