version: '3.7'

services:
  # redis:
  #   container_name: redis
  #   image: 'redis:5.0-alpine'
  #   command: redis-server
  #   volumes:
  #     - 'redis:/data'
  #   ports:
  #     - '6379:6379'
  db:
    image: postgres:14
    container_name: pgdb
    ports:
      - '5432:5432'
    env_file:
      - .env
  web:
    build:
      context: .
      args:
        flask_port: 5000
    container_name: web
    depends_on:
      - db
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: ["python", "app.py"]

# volumes:
#   redis: